version: "3"
services:

  n2n_evn_BIG_VERSION_SMALL_VERSION_rCOMMIT:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BIG_VERSION: ${BIG_VERSION}
        SMALL_VERSION: ${SMALL_VERSION}
        COMMIT: ${COMMIT}
      labels:
        org.opencontainers.image.version: ${BIG_VERSION}_${SMALL_VERSION}_r${COMMIT}
    image: ${REGISTRY}/zctmdc/n2n_lucktu:${BIG_VERSION}_${SMALL_VERSION}_r${COMMIT}

  n2n_evn_v_SMALL_VERSION_rCOMMIT:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BIG_VERSION: ${BIG_VERSION}
        SMALL_VERSION: ${SMALL_VERSION}
        COMMIT: ${COMMIT}
      labels:
        org.opencontainers.image.version: ${BIG_VERSION}_${SMALL_VERSION}_r${COMMIT}
    image: ${REGISTRY}/zctmdc/n2n_lucktu:v.${SMALL_VERSION}_r${COMMIT}

  n2n_evn_v_SMALL_VERSION:
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        org.opencontainers.image.version: v.${SMALL_VERSION}
      args:
        BIG_VERSION: ${BIG_VERSION}
        SMALL_VERSION: ${SMALL_VERSION}
        COMMIT: ${COMMIT}
    image: ${REGISTRY}/zctmdc/n2n_lucktu:v.${SMALL_VERSION}
