version: "3"
services:

  n2n_releases-v2s:
    image: ${REGISTRY}/zctmdc/n2n_lucktu:releases-v2s
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION_B_S_rC: v2s
      labels:
        org.opencontainers.image.version: v2s
      platforms:
        - "linux/amd64"
        - "linux/386"
        - "linux/arm64/v8"
        - "linux/arm/v7"
  n2n_v2s:
    image: ${REGISTRY}/zctmdc/n2n_lucktu:v2s
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION_B_S_rC: v2s
      labels:
        org.opencontainers.image.version: v2s
      platforms:
        - "linux/amd64"
        - "linux/386"
        - "linux/arm64/v8"
        - "linux/arm/v7"

  n2n_releases-v2:
    image: ${REGISTRY}/zctmdc/n2n_lucktu:releases-v2
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION_B_S_rC: v2
      labels:
        org.opencontainers.image.version: v2
      platforms:
        - "linux/amd64"
        - "linux/386"
        - "linux/arm64/v8"
        - "linux/arm/v7"

  n2n_v2:
    image: ${REGISTRY}/zctmdc/n2n_lucktu:v2
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION_B_S_rC: v2
      labels:
        org.opencontainers.image.version: v2
      platforms:
        - "linux/amd64"
        - "linux/386"
        - "linux/arm64/v8"
        - "linux/arm/v7"

  n2n_releases-v1:
    image: ${REGISTRY}/zctmdc/n2n_lucktu:releases-v1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION_B_S_rC: v1
      labels:
        org.opencontainers.image.version: v1
      platforms:
        - "linux/amd64"
        - "linux/386"
        - "linux/arm64/v8"
        - "linux/arm/v7"
  n2n_v1:
    image: ${REGISTRY}/zctmdc/n2n_lucktu:v1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION_B_S_rC: v1
      labels:
        org.opencontainers.image.version: v1
      platforms:
        - "linux/amd64"
        - "linux/386"
        - "linux/arm64/v8"
        - "linux/arm/v7"