version: "3"
services:

  n2n_evn_BIG_VERSION_SMALL_VERSION_rCOMMIT:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BIG_VERSION: ${BUILD_BIG_VERSION}
        SMALL_VERSION: ${BUILD_SMALL_VERSION}
        COMMIT: ${BUILD_COMMIT}
        VERSION_B_S_rC: ${BUILD_VERSION_B_S_rC}
      labels:
        org.opencontainers.image.version: ${BUILD_BIG_VERSION}_${BUILD_SMALL_VERSION}_r${BUILD_COMMIT}
    image: ${REGISTRY}/zctmdc/n2n_lucktu:${BUILD_BIG_VERSION}_${BUILD_SMALL_VERSION}_r${BUILD_COMMIT}

  n2n_evn_v_SMALL_VERSION_rCOMMIT:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BIG_VERSION: ${BUILD_BIG_VERSION}
        SMALL_VERSION: ${BUILD_SMALL_VERSION}
        COMMIT: ${BUILD_COMMIT}
        VERSION_B_S_rC: ${BUILD_VERSION_B_S_rC}
      labels:
        org.opencontainers.image.version: ${BUILD_BIG_VERSION}_${BUILD_SMALL_VERSION}_r${BUILD_COMMIT}
    image: ${REGISTRY}/zctmdc/n2n_lucktu:v.${BUILD_SMALL_VERSION}_r${BUILD_COMMIT}

  n2n_evn_v_SMALL_VERSION:
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        org.opencontainers.image.version: v.${BUILD_SMALL_VERSION}
      args:
        BIG_VERSION: ${BUILD_BIG_VERSION}
        SMALL_VERSION: ${BUILD_SMALL_VERSION}
        COMMIT: ${BUILD_COMMIT}
        VERSION_B_S_rC: ${BUILD_VERSION_B_S_rC}
    image: ${REGISTRY}/zctmdc/n2n_lucktu:v.${BUILD_SMALL_VERSION}
